# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tufie < Formula
  desc "TUFie an Open Source generic TUF client"
  homepage "https://github.com/kairoaraujo/tufie"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kairoaraujo/tufie/releases/download/v0.2.0/tufie_0.2.0_darwin_arm64.tar.gz"
      sha256 "1bb307093a8c7eaf2c5b2f0f89a89d628215570c9f0964e6318a6e0be1d8240a"

      def install
        bin.install "tufie"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kairoaraujo/tufie/releases/download/v0.2.0/tufie_0.2.0_darwin_amd64.tar.gz"
      sha256 "d38df936509e5943883d4b81cdede920c1157cea016838402094a591dbed5c3e"

      def install
        bin.install "tufie"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kairoaraujo/tufie/releases/download/v0.2.0/tufie_0.2.0_linux_arm64.tar.gz"
      sha256 "7820bdb38bcbc00d9b2ded9339e1bb9b045f9d55a13f924b05ffb5c0827e04c1"

      def install
        bin.install "tufie"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kairoaraujo/tufie/releases/download/v0.2.0/tufie_0.2.0_linux_amd64.tar.gz"
      sha256 "440bec7ccdfa716f7c1fb9b8fb1aa8d208a74fe74f42e2c182b11ad21750b950"

      def install
        bin.install "tufie"
      end
    end
  end

  test do
    system "#{bin}/tufie --help"
  end
end
