# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tufie < Formula
  desc "TUFie an Open Source generic TUF client"
  homepage "https://github.com/kairoaraujo/tufie"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kairoaraujo/tufie/releases/download/v0.2.0/tufie_0.2.0_darwin_arm64.tar.gz"
      sha256 "fcdebc01150c6ed1df2b2d25dfd85c9c2840906dd4c6c57c8ec8fc97e28d5236"

      def install
        bin.install "tufie"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kairoaraujo/tufie/releases/download/v0.2.0/tufie_0.2.0_darwin_amd64.tar.gz"
      sha256 "4cd99009ed5bdbb56c7ffc1ac31da0ba064509aae8ef840e52fd8ae2075f896b"

      def install
        bin.install "tufie"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kairoaraujo/tufie/releases/download/v0.2.0/tufie_0.2.0_linux_arm64.tar.gz"
      sha256 "c167f85730ae6ef301546bd81c989d6eec0ff134bd9a276a162c76b49763d5f3"

      def install
        bin.install "tufie"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kairoaraujo/tufie/releases/download/v0.2.0/tufie_0.2.0_linux_amd64.tar.gz"
      sha256 "ac3c1c87e8e1740fa221f47da118f5c8be5e81ff90ffb40af2978fb8a3172524"

      def install
        bin.install "tufie"
      end
    end
  end

  test do
    system "#{bin}/tufie --help"
  end
end
